/* A recursive-descent parser generated by peg 0.1.19 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 57
#line 10 "parse.peg"

#if HAVE_CONFIG_H
#   include <config.h>
#endif

#include "net.h"
#include "types.h"
#include "rinetd.h"
#include "parse.h"

#include <glob.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#define YY_CTX_LOCAL 1
#define YY_CTX_MEMBERS \
    FILE *fp; \
    int currentLine; \
    int isAuthAllow; \
    char *tmpPort, *bindPort, *connectPort; \
    int tmpProto, bindProto, connectProto; \
    int serverTimeout; \
    int keepalive; \
    int dns_refresh_period; \
    int socketMode; \
    char *bindAddress, *connectAddress, *sourceAddress; \
    /* Include tracking */ \
    int includeDepth; \
    char **includedFiles; \
    int includedFilesCount; \
    int includedFilesCapacity; \
    char *currentFile;
#define YY_INPUT(yyctx, buf, result, max_size) \
{ \
    int yyc = fgetc(yyctx->fp); \
    result = (EOF == yyc) ? 0 : (*(buf) = yyc, 1); \
}
#define PARSE_ERROR exit(1);
#define MEMORY_ERROR { \
        logError("could not allocate memory when parsing configuration.\n"); \
        exit(1); \
    }

#if defined __clang__
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wunused-label"
#elif defined __GNUC__
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-label"
#endif

/* Forward declarations for functions called from grammar actions */
struct _yycontext; /* Forward declaration - yycontext typedef defined later */
void parseConfigurationFile(char const *file, struct _yycontext *ctx);
void parseInclude(char const *pattern, struct _yycontext *ctx);
static char *stripQuotes(char const *str);


#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM_R
#define YYPARSEFROM_R	yyparsefrom_r
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy, int yythunkpos)
{
  int pos;
  for (pos= yythunkpos;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy, 0);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_eof(yycontext *yy); /* 57 */
YY_RULE(int) yy_id(yycontext *yy); /* 56 */
YY_RULE(int) yy_label(yycontext *yy); /* 55 */
YY_RULE(int) yy_bare_ipv6(yycontext *yy); /* 54 */
YY_RULE(int) yy_digit(yycontext *yy); /* 53 */
YY_RULE(int) yy_hexdigit(yycontext *yy); /* 52 */
YY_RULE(int) yy_hostname(yycontext *yy); /* 51 */
YY_RULE(int) yy_ipv6(yycontext *yy); /* 50 */
YY_RULE(int) yy_ipv4(yycontext *yy); /* 49 */
YY_RULE(int) yy_name(yycontext *yy); /* 48 */
YY_RULE(int) yy_filename(yycontext *yy); /* 47 */
YY_RULE(int) yy_pattern(yycontext *yy); /* 46 */
YY_RULE(int) yy_auth_key(yycontext *yy); /* 45 */
YY_RULE(int) yy_service(yycontext *yy); /* 44 */
YY_RULE(int) yy_proto(yycontext *yy); /* 43 */
YY_RULE(int) yy_port(yycontext *yy); /* 42 */
YY_RULE(int) yy_octal_number(yycontext *yy); /* 41 */
YY_RULE(int) yy_keepalive_value(yycontext *yy); /* 40 */
YY_RULE(int) yy_number(yycontext *yy); /* 39 */
YY_RULE(int) yy_option_mode(yycontext *yy); /* 38 */
YY_RULE(int) yy_option_dns_refresh(yycontext *yy); /* 37 */
YY_RULE(int) yy_option_keepalive(yycontext *yy); /* 36 */
YY_RULE(int) yy_option_source(yycontext *yy); /* 35 */
YY_RULE(int) yy_option_timeout(yycontext *yy); /* 34 */
YY_RULE(int) yy_option(yycontext *yy); /* 33 */
YY_RULE(int) yy_option_list(yycontext *yy); /* 32 */
YY_RULE(int) yy_full_port(yycontext *yy); /* 31 */
YY_RULE(int) yy_address(yycontext *yy); /* 30 */
YY_RULE(int) yy_unix_path(yycontext *yy); /* 29 */
YY_RULE(int) yy_connect_port(yycontext *yy); /* 28 */
YY_RULE(int) yy_connect_address(yycontext *yy); /* 27 */
YY_RULE(int) yy_unix_connect(yycontext *yy); /* 26 */
YY_RULE(int) yy_bind_port(yycontext *yy); /* 25 */
YY_RULE(int) yy_bind_address(yycontext *yy); /* 24 */
YY_RULE(int) yy_unix_bind(yycontext *yy); /* 23 */
YY_RULE(int) yy_server_options(yycontext *yy); /* 22 */
YY_RULE(int) yy_connect_spec(yycontext *yy); /* 21 */
YY_RULE(int) yy_bind_spec(yycontext *yy); /* 20 */
YY_RULE(int) yy_include_directive(yycontext *yy); /* 19 */
YY_RULE(int) yy_pool_trim_delay(yycontext *yy); /* 18 */
YY_RULE(int) yy_pool_max_free(yycontext *yy); /* 17 */
YY_RULE(int) yy_pool_min_free(yycontext *yy); /* 16 */
YY_RULE(int) yy_dns_refresh_global(yycontext *yy); /* 15 */
YY_RULE(int) yy_buffersize(yycontext *yy); /* 14 */
YY_RULE(int) yy_logcommon(yycontext *yy); /* 13 */
YY_RULE(int) yy_pidfile(yycontext *yy); /* 12 */
YY_RULE(int) yy_logfile(yycontext *yy); /* 11 */
YY_RULE(int) yy_auth_rule(yycontext *yy); /* 10 */
YY_RULE(int) yy_server_rule(yycontext *yy); /* 9 */
YY_RULE(int) yy_comment(yycontext *yy); /* 8 */
YY_RULE(int) yy_command(yycontext *yy); /* 7 */
YY_RULE(int) yy__(yycontext *yy); /* 6 */
YY_RULE(int) yy_invalid_syntax(yycontext *yy); /* 5 */
YY_RULE(int) yy_eol(yycontext *yy); /* 4 */
YY_RULE(int) yy_line(yycontext *yy); /* 3 */
YY_RULE(int) yy_sol(yycontext *yy); /* 2 */
YY_RULE(int) yy_file(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_sol(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_sol\n"));
  {
#line 262
   ++yy->currentLine; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_invalid_syntax(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_invalid_syntax\n"));
  {
#line 236
  
    logError("invalid syntax at line %d: %s\n", yy->currentLine, yytext);
    PARSE_ERROR; /* FIXME */
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_include_directive(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_include_directive\n"));
  {
#line 231
  
    parseInclude(yytext, yy);
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_pool_trim_delay(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_pool_trim_delay\n"));
  {
#line 222
  
    poolTrimDelay = atoi(yytext);
    if (poolTrimDelay < 100 || poolTrimDelay > 300000) {
        logError("invalid pool-trim-delay value %d at line %d (must be 100-300000 ms)\n", poolTrimDelay, yy->currentLine);
        PARSE_ERROR;
    }
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_pool_max_free(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_pool_max_free\n"));
  {
#line 213
  
    poolMaxFree = atoi(yytext);
    if (poolMaxFree < 1 || poolMaxFree > 100000) {
        logError("invalid pool-max-free value %d at line %d (must be 1-100000)\n", poolMaxFree, yy->currentLine);
        PARSE_ERROR;
    }
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_pool_min_free(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_pool_min_free\n"));
  {
#line 204
  
    poolMinFree = atoi(yytext);
    if (poolMinFree < 0 || poolMinFree > 10000) {
        logError("invalid pool-min-free value %d at line %d (must be 0-10000)\n", poolMinFree, yy->currentLine);
        PARSE_ERROR;
    }
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_dns_refresh_global(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_dns_refresh_global\n"));
  {
#line 195
  
    globalDnsRefreshPeriod = atoi(yytext);
    if (globalDnsRefreshPeriod < 0) {
        logError("invalid dns-refresh value at line %d\n", yy->currentLine);
        PARSE_ERROR;
    }
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_buffersize(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_buffersize\n"));
  {
#line 186
  
    bufferSize = atoi(yytext);
    if (bufferSize < 1024 || bufferSize > 1048576) {
        logError("invalid buffer size %d at line %d (must be 1024-1048576)\n", bufferSize, yy->currentLine);
        PARSE_ERROR;
    }
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_logcommon(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_logcommon\n"));
  {
#line 181
  
    logFormatCommon = 1;
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_pidfile(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_pidfile\n"));
  {
#line 174
  
    pidLogFileName = stripQuotes(yytext);
    if (!pidLogFileName)
        MEMORY_ERROR;
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_logfile(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_logfile\n"));
  {
#line 167
  
    logFileName = stripQuotes(yytext);
    if (!logFileName)
        MEMORY_ERROR;
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_auth_key(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_auth_key\n"));
  {
#line 164
   yy->isAuthAllow = (yytext[0] == 'a'); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_auth_rule(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_auth_rule\n"));
  {
#line 144
  
    allRules = (Rule *)
        realloc(allRules, sizeof(Rule) * (allRulesCount + 1));
    if (!allRules)
        MEMORY_ERROR;
    allRules[allRulesCount].pattern = strdup(yytext);
    if (!allRules[allRulesCount].pattern)
        MEMORY_ERROR;
    allRules[allRulesCount].type = yy->isAuthAllow ? allowRule : denyRule;
    if (seTotal > 0) {
        if (seInfo[seTotal - 1].rulesStart == 0 && seInfo[seTotal - 1].rulesCount == 0) {
            seInfo[seTotal - 1].rulesStart = allRulesCount;
        }
        ++seInfo[seTotal - 1].rulesCount;
    } else {
        ++globalRulesCount;
    }
    ++allRulesCount;
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_proto(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_proto\n"));
  {
#line 141
   yy->tmpProto = IPPROTO_TCP; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_proto(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_proto\n"));
  {
#line 140
   yy->tmpProto = IPPROTO_UDP; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_proto(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_proto\n"));
  {
#line 139
   yy->tmpProto = IPPROTO_TCP; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_port(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_port\n"));
  {
#line 138
   yy->tmpPort = strdup(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_option_mode(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_option_mode\n"));
  {
#line 132
   yy->socketMode = (int)strtol(yytext, NULL, 8); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_option_dns_refresh(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_option_dns_refresh\n"));
  {
#line 131
   yy->dns_refresh_period = atoi(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_option_keepalive(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_option_keepalive\n"));
  {
#line 130
   yy->keepalive = (yytext[1] == 'n') ? 1 : 0; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_option_source(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_option_source\n"));
  {
#line 129
   yy->sourceAddress = strdup(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_option_timeout(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_option_timeout\n"));
  {
#line 128
   yy->serverTimeout = atoi(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_connect_port(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_connect_port\n"));
  {
#line 123
   yy->connectPort = yy->tmpPort; yy->connectProto = yy->tmpProto; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_bind_port(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_bind_port\n"));
  {
#line 122
   yy->bindPort = yy->tmpPort; yy->bindProto = yy->tmpProto; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_connect_address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_connect_address\n"));
  {
#line 121
   yy->connectAddress = strdup(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_bind_address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_bind_address\n"));
  {
#line 120
   yy->bindAddress = strdup(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_unix_connect(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_unix_connect\n"));
  {
#line 113
  
    yy->connectAddress = strdup(yytext);
    yy->connectPort = strdup("0");
    yy->connectProto = IPPROTO_TCP;  /* Stream mode for Unix sockets */
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_unix_bind(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_unix_bind\n"));
  {
#line 108
  
    yy->bindAddress = strdup(yytext);
    yy->bindPort = strdup("0");
    yy->bindProto = IPPROTO_TCP;  /* Stream mode for Unix sockets */
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_server_rule(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_server_rule\n"));
  {
#line 76
  
    /* keepalive: -1 = not set (default to on), 0 = off, 1 = on */
    int keepalive = (yy->keepalive == -1) ? 1 : yy->keepalive;

    /* dns_refresh_period: -1 = not set (use global default), >= 0 = explicit value */
    int dns_refresh = (yy->dns_refresh_period == -1)
                      ? globalDnsRefreshPeriod
                      : yy->dns_refresh_period;

    addServer(yy->bindAddress, yy->bindPort, yy->bindProto,
        yy->connectAddress, yy->connectPort, yy->connectProto,
        yy->serverTimeout > 0 ? yy->serverTimeout : RINETD_DEFAULT_UDP_TIMEOUT,
        yy->sourceAddress,
        keepalive, dns_refresh, yy->socketMode);
    free(yy->bindAddress);
    free(yy->connectAddress);
    free(yy->sourceAddress);
    yy->bindAddress = yy->connectAddress = yy->sourceAddress = NULL;
    free(yy->bindPort);
    free(yy->connectPort);
    yy->bindPort = yy->connectPort = NULL;
    yy->serverTimeout = 0;
    yy->keepalive = -1;
    yy->dns_refresh_period = -1;
    yy->socketMode = 0;
;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_eof(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "eof"));  if (!yymatchChar(yy, '\0')) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_id(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "id"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l2;
  yyprintf((stderr, "  ok   %s @ %s\n", "id", yy->__buf+yy->__pos));
  return 1;
  l2:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "id", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_label(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "label"));
  {  int yypos4= yy->__pos, yythunkpos4= yy->__thunkpos;  if (!yy_id(yy)) goto l5;  goto l4;
  l5:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yy_digit(yy)) goto l3;
  }
  l4:;	
  l6:;	
  {  int yypos7= yy->__pos, yythunkpos7= yy->__thunkpos;
  {  int yypos8= yy->__pos, yythunkpos8= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l9;  goto l8;
  l9:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;  if (!yy_id(yy)) goto l10;  goto l8;
  l10:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;  if (!yy_digit(yy)) goto l7;
  }
  l8:;	  goto l6;
  l7:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "label", yy->__buf+yy->__pos));
  return 1;
  l3:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "label", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_bare_ipv6(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "bare_ipv6"));
  l12:;	
  {  int yypos13= yy->__pos, yythunkpos13= yy->__thunkpos;  if (!yy_hexdigit(yy)) goto l13;  goto l12;
  l13:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;
  }  if (!yymatchChar(yy, ':')) goto l11;
  l14:;	
  {  int yypos15= yy->__pos, yythunkpos15= yy->__thunkpos;
  {  int yypos16= yy->__pos, yythunkpos16= yy->__thunkpos;  if (!yy_hexdigit(yy)) goto l17;  goto l16;
  l17:;	  yy->__pos= yypos16; yy->__thunkpos= yythunkpos16;  if (!yymatchChar(yy, ':')) goto l15;
  }
  l16:;	  goto l14;
  l15:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "bare_ipv6", yy->__buf+yy->__pos));
  return 1;
  l11:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bare_ipv6", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_digit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "digit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l18;
  yyprintf((stderr, "  ok   %s @ %s\n", "digit", yy->__buf+yy->__pos));
  return 1;
  l18:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "digit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_hexdigit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "hexdigit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l19;
  yyprintf((stderr, "  ok   %s @ %s\n", "hexdigit", yy->__buf+yy->__pos));
  return 1;
  l19:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "hexdigit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_hostname(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "hostname"));
  l21:;	
  {  int yypos22= yy->__pos, yythunkpos22= yy->__thunkpos;  if (!yy_label(yy)) goto l22;  if (!yymatchChar(yy, '.')) goto l22;  goto l21;
  l22:;	  yy->__pos= yypos22; yy->__thunkpos= yythunkpos22;
  }  if (!yy_name(yy)) goto l20;
  {  int yypos23= yy->__pos, yythunkpos23= yy->__thunkpos;  if (!yymatchChar(yy, '.')) goto l23;  goto l24;
  l23:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;
  }
  l24:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "hostname", yy->__buf+yy->__pos));
  return 1;
  l20:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "hostname", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ipv6(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ipv6"));
  {  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;  if (!yymatchChar(yy, '[')) goto l27;  if (!yy_bare_ipv6(yy)) goto l27;  if (!yymatchChar(yy, ']')) goto l27;  goto l26;
  l27:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;  if (!yy_bare_ipv6(yy)) goto l25;
  }
  l26:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ipv6", yy->__buf+yy->__pos));
  return 1;
  l25:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ipv6", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ipv4(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ipv4"));
  {  int yypos29= yy->__pos, yythunkpos29= yy->__thunkpos;  if (!yy_number(yy)) goto l30;  if (!yymatchChar(yy, '.')) goto l30;  if (!yy_number(yy)) goto l30;  if (!yymatchChar(yy, '.')) goto l30;  if (!yy_number(yy)) goto l30;  if (!yymatchChar(yy, '.')) goto l30;  if (!yy_number(yy)) goto l30;  goto l29;
  l30:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;  if (!yymatchChar(yy, '0')) goto l28;
  }
  l29:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ipv4", yy->__buf+yy->__pos));
  return 1;
  l28:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ipv4", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_name(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "name"));  if (!yy_id(yy)) goto l31;
  l32:;	
  {  int yypos33= yy->__pos, yythunkpos33= yy->__thunkpos;
  {  int yypos34= yy->__pos, yythunkpos34= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l35;  goto l34;
  l35:;	  yy->__pos= yypos34; yy->__thunkpos= yythunkpos34;  if (!yy_id(yy)) goto l36;  goto l34;
  l36:;	  yy->__pos= yypos34; yy->__thunkpos= yythunkpos34;  if (!yy_digit(yy)) goto l33;
  }
  l34:;	  goto l32;
  l33:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "name", yy->__buf+yy->__pos));
  return 1;
  l31:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "name", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_filename(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "filename"));
  {  int yypos38= yy->__pos, yythunkpos38= yy->__thunkpos;  if (!yymatchChar(yy, '"')) goto l39;  if (!yymatchClass(yy, (unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l39;
  l40:;	
  {  int yypos41= yy->__pos, yythunkpos41= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l41;  goto l40;
  l41:;	  yy->__pos= yypos41; yy->__thunkpos= yythunkpos41;
  }  if (!yymatchChar(yy, '"')) goto l39;  goto l38;
  l39:;	  yy->__pos= yypos38; yy->__thunkpos= yythunkpos38;  if (!yymatchClass(yy, (unsigned char *)"\377\331\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l37;
  l42:;	
  {  int yypos43= yy->__pos, yythunkpos43= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\377\331\377\377\376\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l43;  goto l42;
  l43:;	  yy->__pos= yypos43; yy->__thunkpos= yythunkpos43;
  }
  }
  l38:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "filename", yy->__buf+yy->__pos));
  return 1;
  l37:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "filename", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pattern(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pattern"));
  {  int yypos47= yy->__pos, yythunkpos47= yy->__thunkpos;  if (!yy_hexdigit(yy)) goto l48;  goto l47;
  l48:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchChar(yy, '[')) goto l49;  goto l47;
  l49:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchChar(yy, ']')) goto l50;  goto l47;
  l50:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchChar(yy, ':')) goto l51;  goto l47;
  l51:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchChar(yy, '.')) goto l52;  goto l47;
  l52:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\004\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l44;
  }
  l47:;	
  l45:;	
  {  int yypos46= yy->__pos, yythunkpos46= yy->__thunkpos;
  {  int yypos53= yy->__pos, yythunkpos53= yy->__thunkpos;  if (!yy_hexdigit(yy)) goto l54;  goto l53;
  l54:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yymatchChar(yy, '[')) goto l55;  goto l53;
  l55:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yymatchChar(yy, ']')) goto l56;  goto l53;
  l56:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yymatchChar(yy, ':')) goto l57;  goto l53;
  l57:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yymatchChar(yy, '.')) goto l58;  goto l53;
  l58:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\004\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l46;
  }
  l53:;	  goto l45;
  l46:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "pattern", yy->__buf+yy->__pos));
  return 1;
  l44:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pattern", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_auth_key(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "auth_key"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l59;
#undef yytext
#undef yyleng
  }
  {  int yypos60= yy->__pos, yythunkpos60= yy->__thunkpos;  if (!yymatchString(yy, "allow")) goto l61;  goto l60;
  l61:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;  if (!yymatchString(yy, "deny")) goto l59;
  }
  l60:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l59;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_auth_key, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "auth_key", yy->__buf+yy->__pos));
  return 1;
  l59:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "auth_key", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_service(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "service"));  if (!yy_name(yy)) goto l62;
  yyprintf((stderr, "  ok   %s @ %s\n", "service", yy->__buf+yy->__pos));
  return 1;
  l62:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "service", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_proto(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "proto"));
  {  int yypos64= yy->__pos, yythunkpos64= yy->__thunkpos;  if (!yymatchString(yy, "/tcp")) goto l65;  yyDo(yy, yy_1_proto, yy->__begin, yy->__end);  goto l64;
  l65:;	  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;  if (!yymatchString(yy, "/udp")) goto l66;  yyDo(yy, yy_2_proto, yy->__begin, yy->__end);  goto l64;
  l66:;	  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;  if (!yymatchString(yy, "")) goto l63;  yyDo(yy, yy_3_proto, yy->__begin, yy->__end);
  }
  l64:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "proto", yy->__buf+yy->__pos));
  return 1;
  l63:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "proto", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_port(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "port"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l67;
#undef yytext
#undef yyleng
  }
  {  int yypos68= yy->__pos, yythunkpos68= yy->__thunkpos;  if (!yy_number(yy)) goto l69;  goto l68;
  l69:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yy_service(yy)) goto l67;
  }
  l68:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l67;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_port, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "port", yy->__buf+yy->__pos));
  return 1;
  l67:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "port", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_octal_number(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "octal_number"));  if (!yymatchChar(yy, '0')) goto l70;
  l71:;	
  {  int yypos72= yy->__pos, yythunkpos72= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l72;  goto l71;
  l72:;	  yy->__pos= yypos72; yy->__thunkpos= yythunkpos72;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "octal_number", yy->__buf+yy->__pos));
  return 1;
  l70:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "octal_number", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_keepalive_value(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "keepalive_value"));
  {  int yypos74= yy->__pos, yythunkpos74= yy->__thunkpos;  if (!yymatchString(yy, "on")) goto l75;  goto l74;
  l75:;	  yy->__pos= yypos74; yy->__thunkpos= yythunkpos74;  if (!yymatchString(yy, "off")) goto l73;
  }
  l74:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "keepalive_value", yy->__buf+yy->__pos));
  return 1;
  l73:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "keepalive_value", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_number(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "number"));  if (!yy_digit(yy)) goto l76;
  l77:;	
  {  int yypos78= yy->__pos, yythunkpos78= yy->__thunkpos;  if (!yy_digit(yy)) goto l78;  goto l77;
  l78:;	  yy->__pos= yypos78; yy->__thunkpos= yythunkpos78;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "number", yy->__buf+yy->__pos));
  return 1;
  l76:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "number", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option_mode(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option_mode"));  if (!yymatchString(yy, "mode")) goto l79;
  {  int yypos80= yy->__pos, yythunkpos80= yy->__thunkpos;  if (!yy__(yy)) goto l80;  goto l81;
  l80:;	  yy->__pos= yypos80; yy->__thunkpos= yythunkpos80;
  }
  l81:;	  if (!yymatchChar(yy, '=')) goto l79;
  {  int yypos82= yy->__pos, yythunkpos82= yy->__thunkpos;  if (!yy__(yy)) goto l82;  goto l83;
  l82:;	  yy->__pos= yypos82; yy->__thunkpos= yythunkpos82;
  }
  l83:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l79;
#undef yytext
#undef yyleng
  }  if (!yy_octal_number(yy)) goto l79;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l79;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_option_mode, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "option_mode", yy->__buf+yy->__pos));
  return 1;
  l79:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option_mode", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option_dns_refresh(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option_dns_refresh"));  if (!yymatchString(yy, "dns-refresh")) goto l84;
  {  int yypos85= yy->__pos, yythunkpos85= yy->__thunkpos;  if (!yy__(yy)) goto l85;  goto l86;
  l85:;	  yy->__pos= yypos85; yy->__thunkpos= yythunkpos85;
  }
  l86:;	  if (!yymatchChar(yy, '=')) goto l84;
  {  int yypos87= yy->__pos, yythunkpos87= yy->__thunkpos;  if (!yy__(yy)) goto l87;  goto l88;
  l87:;	  yy->__pos= yypos87; yy->__thunkpos= yythunkpos87;
  }
  l88:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l84;
#undef yytext
#undef yyleng
  }  if (!yy_number(yy)) goto l84;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l84;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_option_dns_refresh, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "option_dns_refresh", yy->__buf+yy->__pos));
  return 1;
  l84:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option_dns_refresh", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option_keepalive(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option_keepalive"));  if (!yymatchString(yy, "keepalive")) goto l89;
  {  int yypos90= yy->__pos, yythunkpos90= yy->__thunkpos;  if (!yy__(yy)) goto l90;  goto l91;
  l90:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;
  }
  l91:;	  if (!yymatchChar(yy, '=')) goto l89;
  {  int yypos92= yy->__pos, yythunkpos92= yy->__thunkpos;  if (!yy__(yy)) goto l92;  goto l93;
  l92:;	  yy->__pos= yypos92; yy->__thunkpos= yythunkpos92;
  }
  l93:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l89;
#undef yytext
#undef yyleng
  }  if (!yy_keepalive_value(yy)) goto l89;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l89;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_option_keepalive, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "option_keepalive", yy->__buf+yy->__pos));
  return 1;
  l89:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option_keepalive", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option_source(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option_source"));  if (!yymatchString(yy, "src")) goto l94;
  {  int yypos95= yy->__pos, yythunkpos95= yy->__thunkpos;  if (!yy__(yy)) goto l95;  goto l96;
  l95:;	  yy->__pos= yypos95; yy->__thunkpos= yythunkpos95;
  }
  l96:;	  if (!yymatchChar(yy, '=')) goto l94;
  {  int yypos97= yy->__pos, yythunkpos97= yy->__thunkpos;  if (!yy__(yy)) goto l97;  goto l98;
  l97:;	  yy->__pos= yypos97; yy->__thunkpos= yythunkpos97;
  }
  l98:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l94;
#undef yytext
#undef yyleng
  }  if (!yy_address(yy)) goto l94;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l94;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_option_source, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "option_source", yy->__buf+yy->__pos));
  return 1;
  l94:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option_source", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option_timeout(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option_timeout"));  if (!yymatchString(yy, "timeout")) goto l99;
  {  int yypos100= yy->__pos, yythunkpos100= yy->__thunkpos;  if (!yy__(yy)) goto l100;  goto l101;
  l100:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;
  }
  l101:;	  if (!yymatchChar(yy, '=')) goto l99;
  {  int yypos102= yy->__pos, yythunkpos102= yy->__thunkpos;  if (!yy__(yy)) goto l102;  goto l103;
  l102:;	  yy->__pos= yypos102; yy->__thunkpos= yythunkpos102;
  }
  l103:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l99;
#undef yytext
#undef yyleng
  }  if (!yy_number(yy)) goto l99;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l99;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_option_timeout, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "option_timeout", yy->__buf+yy->__pos));
  return 1;
  l99:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option_timeout", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option"));
  {  int yypos105= yy->__pos, yythunkpos105= yy->__thunkpos;  if (!yy_option_timeout(yy)) goto l106;  goto l105;
  l106:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;  if (!yy_option_source(yy)) goto l107;  goto l105;
  l107:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;  if (!yy_option_keepalive(yy)) goto l108;  goto l105;
  l108:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;  if (!yy_option_dns_refresh(yy)) goto l109;  goto l105;
  l109:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;  if (!yy_option_mode(yy)) goto l104;
  }
  l105:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "option", yy->__buf+yy->__pos));
  return 1;
  l104:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_option_list(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "option_list"));  if (!yy_option(yy)) goto l110;
  {  int yypos111= yy->__pos, yythunkpos111= yy->__thunkpos;
  {  int yypos113= yy->__pos, yythunkpos113= yy->__thunkpos;  if (!yy__(yy)) goto l113;  goto l114;
  l113:;	  yy->__pos= yypos113; yy->__thunkpos= yythunkpos113;
  }
  l114:;	  if (!yymatchChar(yy, ',')) goto l111;
  {  int yypos115= yy->__pos, yythunkpos115= yy->__thunkpos;  if (!yy__(yy)) goto l115;  goto l116;
  l115:;	  yy->__pos= yypos115; yy->__thunkpos= yythunkpos115;
  }
  l116:;	  if (!yy_option_list(yy)) goto l111;  goto l112;
  l111:;	  yy->__pos= yypos111; yy->__thunkpos= yythunkpos111;
  }
  l112:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "option_list", yy->__buf+yy->__pos));
  return 1;
  l110:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "option_list", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_full_port(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "full_port"));  if (!yy_port(yy)) goto l117;  if (!yy_proto(yy)) goto l117;
  yyprintf((stderr, "  ok   %s @ %s\n", "full_port", yy->__buf+yy->__pos));
  return 1;
  l117:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "full_port", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "address"));
  {  int yypos119= yy->__pos, yythunkpos119= yy->__thunkpos;  if (!yy_ipv4(yy)) goto l120;  goto l119;
  l120:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_ipv6(yy)) goto l121;  goto l119;
  l121:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_hostname(yy)) goto l118;
  }
  l119:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "address", yy->__buf+yy->__pos));
  return 1;
  l118:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_unix_path(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "unix_path"));
  {  int yypos123= yy->__pos, yythunkpos123= yy->__thunkpos;  if (!yymatchChar(yy, '@')) goto l124;  if (!yymatchClass(yy, (unsigned char *)"\377\331\377\377\376\377\377\377\377\377\377\327\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l124;
  l125:;	
  {  int yypos126= yy->__pos, yythunkpos126= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\377\331\377\377\376\377\377\377\377\377\377\327\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l126;  goto l125;
  l126:;	  yy->__pos= yypos126; yy->__thunkpos= yythunkpos126;
  }  goto l123;
  l124:;	  yy->__pos= yypos123; yy->__thunkpos= yythunkpos123;  if (!yymatchChar(yy, '/')) goto l122;  if (!yymatchClass(yy, (unsigned char *)"\377\331\377\377\376\377\377\377\377\377\377\327\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l122;
  l127:;	
  {  int yypos128= yy->__pos, yythunkpos128= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\377\331\377\377\376\377\377\377\377\377\377\327\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l128;  goto l127;
  l128:;	  yy->__pos= yypos128; yy->__thunkpos= yythunkpos128;
  }
  }
  l123:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "unix_path", yy->__buf+yy->__pos));
  return 1;
  l122:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unix_path", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_connect_port(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "connect_port"));  if (!yy_full_port(yy)) goto l129;  yyDo(yy, yy_1_connect_port, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "connect_port", yy->__buf+yy->__pos));
  return 1;
  l129:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "connect_port", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_connect_address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "connect_address"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l130;
#undef yytext
#undef yyleng
  }  if (!yy_address(yy)) goto l130;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l130;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_connect_address, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "connect_address", yy->__buf+yy->__pos));
  return 1;
  l130:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "connect_address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_unix_connect(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "unix_connect"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l131;
#undef yytext
#undef yyleng
  }  if (!yymatchString(yy, "unix:")) goto l131;  if (!yy_unix_path(yy)) goto l131;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l131;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_unix_connect, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "unix_connect", yy->__buf+yy->__pos));
  return 1;
  l131:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unix_connect", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_bind_port(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "bind_port"));  if (!yy_full_port(yy)) goto l132;  yyDo(yy, yy_1_bind_port, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "bind_port", yy->__buf+yy->__pos));
  return 1;
  l132:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bind_port", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_bind_address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "bind_address"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l133;
#undef yytext
#undef yyleng
  }  if (!yy_address(yy)) goto l133;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l133;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_bind_address, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "bind_address", yy->__buf+yy->__pos));
  return 1;
  l133:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bind_address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_unix_bind(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "unix_bind"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l134;
#undef yytext
#undef yyleng
  }  if (!yymatchString(yy, "unix:")) goto l134;  if (!yy_unix_path(yy)) goto l134;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l134;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_unix_bind, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "unix_bind", yy->__buf+yy->__pos));
  return 1;
  l134:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unix_bind", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_server_options(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "server_options"));  if (!yymatchChar(yy, '[')) goto l135;
  {  int yypos136= yy->__pos, yythunkpos136= yy->__thunkpos;  if (!yy__(yy)) goto l136;  goto l137;
  l136:;	  yy->__pos= yypos136; yy->__thunkpos= yythunkpos136;
  }
  l137:;	  if (!yy_option_list(yy)) goto l135;
  {  int yypos138= yy->__pos, yythunkpos138= yy->__thunkpos;  if (!yy__(yy)) goto l138;  goto l139;
  l138:;	  yy->__pos= yypos138; yy->__thunkpos= yythunkpos138;
  }
  l139:;	  if (!yymatchChar(yy, ']')) goto l135;
  yyprintf((stderr, "  ok   %s @ %s\n", "server_options", yy->__buf+yy->__pos));
  return 1;
  l135:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "server_options", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_connect_spec(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "connect_spec"));
  {  int yypos141= yy->__pos, yythunkpos141= yy->__thunkpos;  if (!yy_unix_connect(yy)) goto l142;  goto l141;
  l142:;	  yy->__pos= yypos141; yy->__thunkpos= yythunkpos141;  if (!yy_connect_address(yy)) goto l140;  if (!yy__(yy)) goto l140;  if (!yy_connect_port(yy)) goto l140;
  }
  l141:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "connect_spec", yy->__buf+yy->__pos));
  return 1;
  l140:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "connect_spec", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_bind_spec(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "bind_spec"));
  {  int yypos144= yy->__pos, yythunkpos144= yy->__thunkpos;  if (!yy_unix_bind(yy)) goto l145;  goto l144;
  l145:;	  yy->__pos= yypos144; yy->__thunkpos= yythunkpos144;  if (!yy_bind_address(yy)) goto l143;  if (!yy__(yy)) goto l143;  if (!yy_bind_port(yy)) goto l143;
  }
  l144:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "bind_spec", yy->__buf+yy->__pos));
  return 1;
  l143:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bind_spec", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_include_directive(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "include_directive"));  if (!yymatchString(yy, "include")) goto l146;  if (!yy__(yy)) goto l146;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l146;
#undef yytext
#undef yyleng
  }  if (!yy_filename(yy)) goto l146;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l146;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_include_directive, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "include_directive", yy->__buf+yy->__pos));
  return 1;
  l146:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "include_directive", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pool_trim_delay(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pool_trim_delay"));  if (!yymatchString(yy, "pool-trim-delay")) goto l147;  if (!yy__(yy)) goto l147;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l147;
#undef yytext
#undef yyleng
  }  if (!yy_number(yy)) goto l147;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l147;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_pool_trim_delay, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "pool_trim_delay", yy->__buf+yy->__pos));
  return 1;
  l147:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pool_trim_delay", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pool_max_free(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pool_max_free"));  if (!yymatchString(yy, "pool-max-free")) goto l148;  if (!yy__(yy)) goto l148;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l148;
#undef yytext
#undef yyleng
  }  if (!yy_number(yy)) goto l148;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l148;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_pool_max_free, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "pool_max_free", yy->__buf+yy->__pos));
  return 1;
  l148:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pool_max_free", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pool_min_free(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pool_min_free"));  if (!yymatchString(yy, "pool-min-free")) goto l149;  if (!yy__(yy)) goto l149;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l149;
#undef yytext
#undef yyleng
  }  if (!yy_number(yy)) goto l149;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l149;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_pool_min_free, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "pool_min_free", yy->__buf+yy->__pos));
  return 1;
  l149:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pool_min_free", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_dns_refresh_global(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "dns_refresh_global"));  if (!yymatchString(yy, "dns-refresh")) goto l150;  if (!yy__(yy)) goto l150;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l150;
#undef yytext
#undef yyleng
  }  if (!yy_number(yy)) goto l150;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l150;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_dns_refresh_global, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "dns_refresh_global", yy->__buf+yy->__pos));
  return 1;
  l150:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "dns_refresh_global", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_buffersize(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "buffersize"));  if (!yymatchString(yy, "buffersize")) goto l151;  if (!yy__(yy)) goto l151;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l151;
#undef yytext
#undef yyleng
  }  if (!yy_number(yy)) goto l151;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l151;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_buffersize, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "buffersize", yy->__buf+yy->__pos));
  return 1;
  l151:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "buffersize", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_logcommon(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "logcommon"));  if (!yymatchString(yy, "logcommon")) goto l152;  yyDo(yy, yy_1_logcommon, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "logcommon", yy->__buf+yy->__pos));
  return 1;
  l152:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "logcommon", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pidfile(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pidfile"));  if (!yymatchString(yy, "pidfile")) goto l153;  if (!yy__(yy)) goto l153;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l153;
#undef yytext
#undef yyleng
  }  if (!yy_filename(yy)) goto l153;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l153;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_pidfile, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "pidfile", yy->__buf+yy->__pos));
  return 1;
  l153:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pidfile", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_logfile(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "logfile"));  if (!yymatchString(yy, "logfile")) goto l154;  if (!yy__(yy)) goto l154;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l154;
#undef yytext
#undef yyleng
  }  if (!yy_filename(yy)) goto l154;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l154;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_logfile, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "logfile", yy->__buf+yy->__pos));
  return 1;
  l154:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "logfile", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_auth_rule(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "auth_rule"));  if (!yy_auth_key(yy)) goto l155;  if (!yy__(yy)) goto l155;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l155;
#undef yytext
#undef yyleng
  }  if (!yy_pattern(yy)) goto l155;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l155;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_auth_rule, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "auth_rule", yy->__buf+yy->__pos));
  return 1;
  l155:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "auth_rule", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_server_rule(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "server_rule"));  if (!yy_bind_spec(yy)) goto l156;  if (!yy__(yy)) goto l156;  if (!yy_connect_spec(yy)) goto l156;
  {  int yypos157= yy->__pos, yythunkpos157= yy->__thunkpos;
  {  int yypos159= yy->__pos, yythunkpos159= yy->__thunkpos;  if (!yy__(yy)) goto l159;  goto l160;
  l159:;	  yy->__pos= yypos159; yy->__thunkpos= yythunkpos159;
  }
  l160:;	  if (!yy_server_options(yy)) goto l157;  goto l158;
  l157:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;
  }
  l158:;	  yyDo(yy, yy_1_server_rule, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "server_rule", yy->__buf+yy->__pos));
  return 1;
  l156:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "server_rule", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_comment(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "comment"));  if (!yymatchChar(yy, '#')) goto l161;
  l162:;	
  {  int yypos163= yy->__pos, yythunkpos163= yy->__thunkpos;
  {  int yypos164= yy->__pos, yythunkpos164= yy->__thunkpos;  if (!yy_eol(yy)) goto l164;  goto l163;
  l164:;	  yy->__pos= yypos164; yy->__thunkpos= yythunkpos164;
  }  if (!yymatchDot(yy)) goto l163;  goto l162;
  l163:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", yy->__buf+yy->__pos));
  return 1;
  l161:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_command(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "command"));
  {  int yypos166= yy->__pos, yythunkpos166= yy->__thunkpos;  if (!yy_server_rule(yy)) goto l167;  goto l166;
  l167:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_auth_rule(yy)) goto l168;  goto l166;
  l168:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_logfile(yy)) goto l169;  goto l166;
  l169:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_pidfile(yy)) goto l170;  goto l166;
  l170:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_logcommon(yy)) goto l171;  goto l166;
  l171:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_buffersize(yy)) goto l172;  goto l166;
  l172:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_dns_refresh_global(yy)) goto l173;  goto l166;
  l173:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_pool_min_free(yy)) goto l174;  goto l166;
  l174:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_pool_max_free(yy)) goto l175;  goto l166;
  l175:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_pool_trim_delay(yy)) goto l176;  goto l166;
  l176:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  if (!yy_include_directive(yy)) goto l165;
  }
  l166:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "command", yy->__buf+yy->__pos));
  return 1;
  l165:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "command", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "_"));  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l177;
  l178:;	
  {  int yypos179= yy->__pos, yythunkpos179= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l179;  goto l178;
  l179:;	  yy->__pos= yypos179; yy->__thunkpos= yythunkpos179;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
  l177:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_invalid_syntax(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "invalid_syntax"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l180;
#undef yytext
#undef yyleng
  }
  {  int yypos183= yy->__pos, yythunkpos183= yy->__thunkpos;  if (!yy_eol(yy)) goto l183;  goto l180;
  l183:;	  yy->__pos= yypos183; yy->__thunkpos= yythunkpos183;
  }  if (!yymatchDot(yy)) goto l180;
  l181:;	
  {  int yypos182= yy->__pos, yythunkpos182= yy->__thunkpos;
  {  int yypos184= yy->__pos, yythunkpos184= yy->__thunkpos;  if (!yy_eol(yy)) goto l184;  goto l182;
  l184:;	  yy->__pos= yypos184; yy->__thunkpos= yythunkpos184;
  }  if (!yymatchDot(yy)) goto l182;  goto l181;
  l182:;	  yy->__pos= yypos182; yy->__thunkpos= yythunkpos182;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l180;
#undef yytext
#undef yyleng
  }  if (!yy_eol(yy)) goto l180;  yyDo(yy, yy_1_invalid_syntax, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "invalid_syntax", yy->__buf+yy->__pos));
  return 1;
  l180:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "invalid_syntax", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_eol(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "eol"));
  {  int yypos186= yy->__pos, yythunkpos186= yy->__thunkpos;
  {  int yypos188= yy->__pos, yythunkpos188= yy->__thunkpos;  if (!yymatchChar(yy, '\r')) goto l188;  goto l189;
  l188:;	  yy->__pos= yypos188; yy->__thunkpos= yythunkpos188;
  }
  l189:;	  if (!yymatchChar(yy, '\n')) goto l187;  goto l186;
  l187:;	  yy->__pos= yypos186; yy->__thunkpos= yythunkpos186;  if (!yy_eof(yy)) goto l185;
  }
  l186:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 1;
  l185:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_line(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "line"));
  {  int yypos191= yy->__pos, yythunkpos191= yy->__thunkpos;  if (!yy__(yy)) goto l191;  goto l192;
  l191:;	  yy->__pos= yypos191; yy->__thunkpos= yythunkpos191;
  }
  l192:;	
  {  int yypos193= yy->__pos, yythunkpos193= yy->__thunkpos;  if (!yy_command(yy)) goto l193;
  {  int yypos195= yy->__pos, yythunkpos195= yy->__thunkpos;  if (!yy__(yy)) goto l195;  goto l196;
  l195:;	  yy->__pos= yypos195; yy->__thunkpos= yythunkpos195;
  }
  l196:;	  goto l194;
  l193:;	  yy->__pos= yypos193; yy->__thunkpos= yythunkpos193;
  }
  l194:;	
  {  int yypos197= yy->__pos, yythunkpos197= yy->__thunkpos;  if (!yy_comment(yy)) goto l197;  goto l198;
  l197:;	  yy->__pos= yypos197; yy->__thunkpos= yythunkpos197;
  }
  l198:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "line", yy->__buf+yy->__pos));
  return 1;
  l190:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "line", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_sol(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "sol"));  yyDo(yy, yy_1_sol, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "sol", yy->__buf+yy->__pos));
  return 1;
  l199:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sol", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_file(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "file"));
  l201:;	
  {  int yypos202= yy->__pos, yythunkpos202= yy->__thunkpos;  if (!yy_sol(yy)) goto l202;
  {  int yypos203= yy->__pos, yythunkpos203= yy->__thunkpos;  if (!yy_line(yy)) goto l204;  if (!yy_eol(yy)) goto l204;  goto l203;
  l204:;	  yy->__pos= yypos203; yy->__thunkpos= yythunkpos203;  if (!yy_invalid_syntax(yy)) goto l202;
  }
  l203:;	  goto l201;
  l202:;	  yy->__pos= yypos202; yy->__thunkpos= yythunkpos202;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "file", yy->__buf+yy->__pos));
  return 1;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM_R(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok, yythunkpos;
  YYSTYPE *yyval;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__val= yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yythunkpos= yyctx->__thunkpos;
  yyval= yyctx->__val;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx, yythunkpos);
  yyctx->__thunkpos= yythunkpos;
  yyctx->__val= yyval;
  return yyok;
}

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= YYPARSEFROM_R(YY_CTX_ARG_ yystart);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_file);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 266 "parse.peg"


/* Utility functions for include directive support */

/* Check if file already included (circular detection) */
static int isFileIncluded(yycontext *ctx, char const *canonical_path)
{
    for (int i = 0; i < ctx->includedFilesCount; i++) {
        if (strcmp(ctx->includedFiles[i], canonical_path) == 0) {
            return 1;
        }
    }
    return 0;
}

/* Add file to included list */
static void addIncludedFile(yycontext *ctx, char const *canonical_path)
{
    /* Grow array if needed */
    if (ctx->includedFilesCount >= ctx->includedFilesCapacity) {
        int new_capacity = ctx->includedFilesCapacity == 0 ? 16 : ctx->includedFilesCapacity * 2;
        char **new_array = realloc(ctx->includedFiles, new_capacity * sizeof(char*));
        if (!new_array)
            MEMORY_ERROR;
        ctx->includedFiles = new_array;
        ctx->includedFilesCapacity = new_capacity;
    }

    /* Add to list */
    ctx->includedFiles[ctx->includedFilesCount++] = strdup(canonical_path);
}

/* Strip quotes from filename */
static char *stripQuotes(char const *str)
{
    size_t len = strlen(str);
    if (len >= 2 && str[0] == '"' && str[len-1] == '"') {
        char *result = malloc(len - 1);
        if (!result) MEMORY_ERROR;
        memcpy(result, str + 1, len - 2);
        result[len - 2] = '\0';
        return result;
    }
    return strdup(str);
}

/* Resolve relative paths based on current file's directory */
static char *resolveIncludePath(char const *pattern, char const *current_file)
{
    /* If absolute path, return as-is */
    if (pattern[0] == '/')
        return strdup(pattern);

    /* Extract directory from current_file */
    char *dir = strdup(current_file);
    char *last_slash = strrchr(dir, '/');
    if (last_slash) {
        *last_slash = '\0';
    } else {
        /* Current file has no directory component, use current working directory */
        free(dir);
        return strdup(pattern);
    }

    /* Construct absolute path: dir/pattern */
    size_t len = strlen(dir) + strlen(pattern) + 2;
    char *result = malloc(len);
    if (!result) MEMORY_ERROR;
    snprintf(result, len, "%s/%s", dir, pattern);
    free(dir);
    return result;
}

/* Free included files list */
static void freeIncludedFiles(yycontext *ctx)
{
    for (int i = 0; i < ctx->includedFilesCount; i++)
        free(ctx->includedFiles[i]);
    free(ctx->includedFiles);
    ctx->includedFiles = NULL;
    ctx->includedFilesCount = 0;
    ctx->includedFilesCapacity = 0;
}

/* Handle include directive - expand pattern and parse matched files */
void parseInclude(char const *pattern, yycontext *ctx)
{
    /* 1. Check recursion depth */
    if (ctx->includeDepth >= MAX_INCLUDE_DEPTH) {
        logError("maximum include depth (%d) exceeded at %s:%d\n", MAX_INCLUDE_DEPTH, ctx->currentFile, ctx->currentLine);
        PARSE_ERROR;
    }

    /* 2. Strip quotes from pattern if present */
    char *unquoted_pattern = stripQuotes(pattern);

    /* 3. Convert to absolute path if relative */
    char *abs_pattern = resolveIncludePath(unquoted_pattern, ctx->currentFile);

    /* 4. Expand glob pattern */
    glob_t glob_result;
    int glob_flags = GLOB_TILDE | GLOB_BRACE;
    int ret = glob(abs_pattern, glob_flags, NULL, &glob_result);

    if (ret == GLOB_NOMATCH) {
        /* No files match - just log warning and continue */
        logWarning("include pattern matches no files: %s at %s:%d\n", pattern, ctx->currentFile, ctx->currentLine);
        free(abs_pattern);
        free(unquoted_pattern);
        return;
    } else if (ret != 0) {
        logError("error expanding include pattern: %s at %s:%d\n", pattern, ctx->currentFile, ctx->currentLine);
        free(abs_pattern);
        free(unquoted_pattern);
        PARSE_ERROR;
    }

    /* 5. Process each matched file */
    for (size_t i = 0; i < glob_result.gl_pathc; i++) {
        char *file = glob_result.gl_pathv[i];

        /* Skip directories */
        struct stat st;
        if (stat(file, &st) != 0) {
            logError("cannot stat include file: %s at %s:%d\n", file, ctx->currentFile, ctx->currentLine);
            globfree(&glob_result);
            free(abs_pattern);
            free(unquoted_pattern);
            PARSE_ERROR;
        }

        if (S_ISDIR(st.st_mode))
            continue;  /* Skip directories silently */

        /* Check for circular includes */
        char *canonical = realpath(file, NULL);
        if (!canonical) {
            logError("cannot resolve include file: %s at %s:%d\n", file, ctx->currentFile, ctx->currentLine);
            globfree(&glob_result);
            free(abs_pattern);
            free(unquoted_pattern);
            PARSE_ERROR;
        }

        if (isFileIncluded(ctx, canonical)) {
            logError("circular include detected: %s at %s:%d\n", file, ctx->currentFile, ctx->currentLine);
            free(canonical);
            globfree(&glob_result);
            free(abs_pattern);
            free(unquoted_pattern);
            PARSE_ERROR;
        }

        /* Add to included files list */
        addIncludedFile(ctx, canonical);

        /* Parse the included file */
        parseConfigurationFile(file, ctx);

        free(canonical);
    }

    globfree(&glob_result);
    free(abs_pattern);
    free(unquoted_pattern);
}

/* Internal function for parsing a single config file (supports recursion) */
void parseConfigurationFile(char const *file, yycontext *ctx)
{
    FILE *in = fopen(file, "r");
    if (!in) {
        logError("could not open configuration file %s at %s:%d\n", file, ctx->currentFile, ctx->currentLine);
        exit(1);
    }

    /* Save current state */
    FILE *saved_fp = ctx->fp;
    int saved_line = ctx->currentLine;
    char *saved_file = ctx->currentFile;

    /* Set new state */
    ctx->fp = in;
    ctx->currentLine = 0;  /* Will be incremented by sol rule */
    ctx->currentFile = strdup(file);
    ctx->includeDepth++;

    /* Parse the file */
    if (!yyparse(ctx)) {
        logError("invalid syntax in file %s, line %d.\n",
                 ctx->currentFile, ctx->currentLine);
        exit(1);
    }

    /* Restore state */
    fclose(in);
    free(ctx->currentFile);
    ctx->currentFile = saved_file;
    ctx->currentLine = saved_line;
    ctx->fp = saved_fp;
    ctx->includeDepth--;
}

/* Main entry point for configuration parsing */
void parseConfiguration(char const *file)
{
    yycontext ctx;
    memset(&ctx, 0, sizeof(yycontext));
    ctx.keepalive = -1;
    ctx.dns_refresh_period = -1;

    /* Initialize include tracking */
    ctx.includeDepth = 0;
    ctx.includedFiles = NULL;
    ctx.includedFilesCount = 0;
    ctx.includedFilesCapacity = 0;
    ctx.currentFile = strdup(file);

    /* Add main config file to included list to prevent self-inclusion */
    char *canonical = realpath(file, NULL);
    if (canonical) {
        addIncludedFile(&ctx, canonical);
        free(canonical);
    }

    /* Parse main file */
    parseConfigurationFile(file, &ctx);

    /* Cleanup */
    free(ctx.currentFile);
    freeIncludedFiles(&ctx);
    yyrelease(&ctx);

    /* Avoid warnings for these unused functions */
    (void)yySet; (void)yyPush; (void)yyPop; (void)yyAccept;
}


